version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=BitcoinUSDRate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/bit-rate
    ports:
      - "8000:8000"
    depends_on:
      - db    